---
- name: Add drupal.vcl for varnish
  template: src=drupal.vcl.j2 dest={{ varnish_config_path }}/drupal.vcl
  when: varnish_drupal_vcl_enable
  notify: restart varnish


- name: Remove ulimit from init script.
  lineinfile: dest=/etc/init.d/varnish
              line="{{ item }}"
              state=absent
  with_items:
    - "ulimit -n ${NFILES:-131072}"
    - "ulimit -l ${MEMLOCK:-82000}"
  when: varnish_remove_ulimit
